### ISSUE TITLE
Syntax highlighting breaks

### ISSUE THREAD

**Issue by rrdelaney** [chenglou/language-reason#1]
There's a weird case where the syntax highlighting breaks with labelled arguments: 

<img width="1440" alt="screen shot 2017-05-31 at 5 22 02 pm" src="https://cloud.githubusercontent.com/assets/6325382/26659492/d4cf22a8-4625-11e7-8408-6087b0715ec5.png">

[Repro File](https://github.com/rrdelaney/ReasonablyTyped/blob/340a82a9ac92367ce74ab9e4e5423081b306cd5f/src/render.re)

**Comment by chenglou** [comment]
Yep. It's from the old syntax highlighting file. I believe @freebroccolo was planning a new version

**Comment by TheSpyder** [comment]
Any progress on this? It seems to break every time I define a function with labelled arguments.

**Comment by TheSpyder** [comment]
I've been using vscode, installed atom to see if it was any better there but of course the syntax definitions are shared 🙃

**Comment by ghost** [comment]
> Any progress on this?

Part of the delay is due to the fact that I've been rewriting the syntax highlighter from scratch in order to be more maintainable and to be able to share a common highlighting core with OCaml. I have made [very good progress](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/syntaxes/ocaml.ts) on this but it's probably not going to be ready for awhile longer (maybe another week or so). I'll see if I can just make a small change to fix this particular issue until the rewrite is ready.

**Comment by chenglou** [comment]
We're planning a syntax revamp, so this can be postponed for now. The highlighting looks fine on the new syntax

**Comment by TheSpyder** [comment]
@freebroccolo is your updated work viable to develop with? This bugs me quite frequently (I love labelled arguments) and I grow tired of working with my files that are completely messed up due to it. I'd rather not wait for the syntax revamp.

I just discovered that putting the labelled arguments last in the declaration list mostly works around the issue, but that's still annoying.

**Comment by ghost** [comment]
@TheSpyder for OCaml syntax it is but unfortunately I've been very busy lately and haven't had much time lately to finish up the Reason part of that. Given that the syntax is going to be changing soon I think it might be better to wait before putting too much more effort into it since a lot of it might have to be rewritten. But the existing grammar can probably be modified to fix this in the meantime.

@chenglou what is the ETA on the new syntax?

**Comment by chenglou** [comment]
A few more weeks

**Comment by TheSpyder** [comment]
@freebroccolo fair enough. If it's not hard to fix though the double colon change would be _really_ nice to have when I start showing my code to other developers at my company ;)

**Comment by rrdelaney** [comment]
<img width="773" alt="screen shot 2017-09-10 at 10 56 48 pm" src="https://user-images.githubusercontent.com/6325382/30260298-5df2f208-967b-11e7-9941-64be08911ae8.png">

Looks like this was fixed :D

**Comment by TheSpyder** [comment]
confirmed, I hadn't loaded vscode in a week or so but the 1.0 plugin version does fix it :)
